# Generated by Django 5.2.4 on 2025-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonumbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
