# Generated by Django 5.2.4 on 2025-07-11 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonumbers', '0004_searchsubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableresult',
            old_name='plate_number',
            new_name='plate',
        ),
        migrations.RemoveField(
            model_name='availableresult',
            name='region',
        ),
        migrations.RemoveField(
            model_name='availableresult',
            name='user_search',
        ),
        migrations.RemoveField(
            model_name='availableresult',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='availableresult',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='availableresult',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='availableresult',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_results', to='autonumbers.searchsubscription'),
        ),
    ]
